= Run multiple KinD clusters on Lima

Original blog post: https://baptistout.net/posts/kubernetes-clusters-on-macos-with-loadbalancer-without-docker-desktop/

== Prerequisites
Download and install the following tools, in addition to what is explained in the blog:

- kind
- direnv


== Using the scripts

First, take a look at the environment variables in `.envrc` and change the value of $LIMA_WORKDIR to the path of the cloned repo on your machine.

Most of the scripts are available with `Make` targets.

List all the targets with
```bash
make
```

Initialize the env vars for this directory:

```bash
direnv allow .
```

=== MacBook preparation

Run the following make target to create a local work dir on your machine, where some docker images will be saved and where public images will be mirrored:
```bash
mk prepare-mac-host
```

Install the Lima CLI with:

```bash
make dl-install-lima 0.12.0
```

=== Create/Start/Stop/Delete the Lima VM
```bash
make create
make stop
make start
make delete
```

=== Spin up a new KinD cluster
```bash
#make kind-create <id> <name>
make kind-create 1 1-istio
make kind-create 2 2-gloo-edge
make kind-create 3 3-gloo-mesh-mgmt
make kind-create 4 4-gloo-mesh-cluster1
make kind-create 5 5-gloo-mesh-cluster2
```

=== Configure the network E2E
```bash
make config-network-end-to-end
```

=== Test connectivity E2E
```bash
make test
make clean-test
```
