= Run multiple KinD clusters on Lima

Original blog post: https://baptistout.net/posts/kubernetes-clusters-on-macos-with-loadbalancer-without-docker-desktop/

== Prerequisites
Download and install the following tools, in addition to what is explained in the blog:

- https://kind.sigs.k8s.io/[kind] -> `brew install kind`
- https://direnv.net/[direnv] -> `brew install direnv`
- https://baptistout.net/posts/kubernetes-clusters-on-macos-with-loadbalancer-without-docker-desktop/#_setup_part_3_the_docker_cli[docker CLI] (not docker desktop, just the CLI) -> `brew install docker`


== Getting started

First, take a look at the environment variables in `.envrc` and change the value of $LIMA_WORKDIR to the path of the cloned repo on your machine.

Initialize the env vars for this directory:

```bash
direnv allow .
```

=== Using the scripts

Most of the scripts are available with `Make` targets.

List all the targets with
```bash
# Safely run `make` to list all the targets
make
```


=== MacBook preparation

Run the following make target to create a local work dir on your machine. A few docker images will be saved locally as archives. This will take a few minutes.

```bash
make prepare-mac-host
```

=== Lima CLI
Install the Lima CLI with:

```bash
make dl-install-lima 0.14.2
```

This will download the lima command-line (limactl) and save it in your workdir. Then the makefile targets will use this binary.

=== Create and start the Lima VM
make delete


Other targets include:
```bash
make create
make start
```

=== Configure the network E2E
The following command will:

- configure the network on your MacBook machine to allow access to the Lima VM.
- pre-configures the Kind network bridge on the Lima VM so that it's connected to the local docker registries.
- configure the network on the Lima VM to allow access from the MacBook host to the KinD clusters.

```bash
make config-network-end-to-end
```

Run this command everytime you restart the Lima VM.

=== Spin up a new KinD cluster
```bash
#make kind-create <id> <name>
make kind-create 1 1-istio
make kind-create 2 2-gloo-edge
make kind-create 3 3-gloo-mesh-mgmt
make kind-create 4 4-gloo-mesh-cluster1
make kind-create 5 5-gloo-mesh-cluster2
```

The `kind-create` script takes care of:

- creating a new KinD cluster
- configuring MetalLB so that you can use a LoadBalancer service
- configuring the KinD network bridge to be connected to the local docker registries

=== Test connectivity E2E
The following command will help you test the connectivity end-to-end.

It will deploy an nginx instance (pod) on the current cluster, expose the nginx service with a Service type LoadBalancer, and then curl the nginx service from the MacBook host.

```bash
make test
make clean-test
```

=== Manage KinD clusters

```bash
# list all the kind clusters:
make kind-list
# delete a specific kind cluster with:
make kind-delete 1-istio
# delete all kind cluster with:
make kind-delete-all
````