docker stop "${USDOCKERPKGDEV_CACHE_NAME}"
docker stop "${GCRIO_CACHE_NAME}"
docker stop "${QUAYIO_CACHE_NAME}"
docker stop "${DOCKERIO_CACHE_NAME}"
docker stop "${DOCKERIO_REG1_CACHE_NAME}"
docker stop "${LOCALHOST_CACHE_NAME}"
docker stop "${USCENTRAL1DOCKERPKGDEV_CACHE_NAME}"